on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
      s3_bucket:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

jobs:
  deploy-to-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: rlespinasse/github-slug-action@v3.x
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: Zip lambda
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ github.event.inputs.region}}

      - name: Copy zip to S3 with the AWS CLI
        run: |
          aws s3 cp ./bundle.zip s3://${{ inputs.s3_bucket }}