on:
  workflow_call:
    inputs:
      region:
        required: true
        type: string
      s3_bucket:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy-to-lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: rlespinasse/github-slug-action@v3.x
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ inputs.region}}

      - name: Zip and upload to S3
        run: |
          zip -q -r ./bundle.zip ./
          aws s3 cp ./bundle.zip s3://${{ inputs.s3_bucket }}

      - name: Deploy Cloudformation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: FulfillmentsApi-${{env.GITHUB_REF_NAME}}
          template: cloudformation_template.yml
          no-fail-on-empty-changeset: "1"
          parameter-overrides: