on:
  push:
    branches:
      - "master"

jobs:
  rubocop-test:
    runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Run Rubocop
        run: bundle exec rubocop --parallel
  rspec-test:
    needs: rubocop-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: rrainn/dynamodb-action@v2.0.0
        with:
          port: 8001
          cors: '*'
      - name: Run tests
        env:
          PROJECT_ENV: local
        run: bundle exec rspec
  deploy-to-lambda:
    needs: rspec-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Zip
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./
      - name: Deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-2
          function_name: fulfillments-api
          zip_file: bundle.zip