name: Test and Deploy

on:
  push:
    branches:
      - master
      - dev

jobs:
  test:
    uses: machineboy2045/lambda-ruby-test/.github/workflows/test.yml@master
  deploy:
    needs: test
    uses: machineboy2045/lambda-ruby-test/.github/workflows/deploy_lambda.yml@master
    with:
      s3_bucket: fulfillments-api-lambda
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}